### ISSUE TITLE
Plugin doesn't install

### ISSUE THREAD

**Issue by ThorstenBrand** [evaherbst/MyoGenerator#9]
Thank you for making this addon available!

When downloading the code as a .zip-file and installing it via the instructions, it still isn't registered inside Blender.

A workaround for me to get it running was to move all code files from 
`Blender\2.91\scripts\addons\MyoGenerator-main\AddonFolder`
to
`Blender\2.91\scripts\addons\MyoGenerator-main`
and to replace all references in the files to `AddonFolder` with `.`.

As is, the `__init__.py` seems not to be found by Blender.

**Comment by evaherbst** [comment]
Hello,
The installation as described (downloading folder, zipping AddOn Folder and selecting that folder for the installation) works for me. Did you instead select the main folder for the add-on installation?
